apiVersion: v1
kind: ServiceAccount
metadata:
  name: eos-oncallers
  namespace: noc-tools
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::097678204211:role/eos-oncallers-k8s
  labels:
    app: eos-oncallers
    team: noc
