apiVersion: v1
kind: Service
metadata:
  name: eos-oncallers
  namespace: noc-tools
  labels:
    app: eos-oncallers
    team: noc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: eos-oncallers
